all:
  hosts:
    vm1:
      ansible_host: 51.250.111.226
      ansible_user: zolotorevnd
      ansible_ssh_private_key_file: /home/zolotorev/.ssh/id_ed25519.pub
    vm2:
      ansible_host: 89.169.179.249
      ansible_user: zolotorevnd
      ansible_ssh_private_key_file: /home/zolotorev/.ssh/id_ed25519.pub