all:
  hosts:
    vm1:
      ansible_host: 158.160.1.70
      ansible_user: zolotorevnd
      ansible_ssh_private_key_file: /home/zolotorev/.ssh/id_ed25519.pub
    vm2:
      ansible_host: 130.193.53.225
      ansible_user: zolotorevnd
      ansible_ssh_private_key_file: /home/zolotorev/.ssh/id_ed25519.pub